apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: project-1
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/
              name: pv001
      volumes:
        - name: pv001
          persistentVolumeClaim:
            claimName: pvc001
---

apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: project-1
spec:
  selector:
    app: httpd
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
