apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: project-2
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
        finalizers: null
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
  namespace: project-2
spec:
  ports:
  - port: 3306
    name: mysql-service
  clusterIP: None
  selector:
    app: mysql
