# Create the PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  namespace: project-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv001/
  storageClassName: "standard"

---

# Create the PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001
  namespace: project-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "standard"
  volumeName: pv001
